### PR TITLE
Fix indexing of envelopes that cross the dateline

### LINKED ISSUE #206: Envelopes across the dateline wrap the wrong way
I happened to notice that there was an Alaska CRM collection that showed up on the map in the collection detail view with its geometry wrapped around the planet instead of across the dateline as intended.

Upon further investigation, it doesn't seem possible to use elasticsearch's `envelope` type for geometries that cross the dateline.

Here are steps to reproduce the issue against ES directly. It inserts what should be the same shape twice, once with type `envelope` and once with `polygon`:

```
PUT space_test
{
   "mappings": {
      "my_type": {
         "properties": {
            "location": {
               "type": "geo_shape"
            }
         }
      }
   }
}

PUT space_test/my_type/1
{
    "location": {
        "type": "envelope",
        "coordinates": [[160, 70], [-160, 50]]
    }
}

PUT space_test/my_type/2
{
    "location": {
        "type": "polygon",
        "coordinates": [[[160, 50], [-160, 50], [-160, 70], [160, 70], [160, 50]]]
    }
}

GET space_test/my_type/_search
{
   "query": {
      "bool": {
         "must": {
            "match_all": {}
         },
         "filter": {
            "geo_shape": {
               "location": {
                  "shape": {
                     "type": "envelope",
                     "coordinates": [[-180, 65], [-170, 55]]
                  },
                  "relation": "intersects"
               }
            }
         }
      }
   }
}
```

The query only returns document 2.

Sadly, the way our api inserts geometries so far is exclusively as `envelope`s... Bummer.

### PR DESCRIPTION
**Pull request by mcquinne**
Resolves #206

### CODE REVIEW

File: api/src/main/groovy/ncei/onestop/api/service/MetadataParser.groovy [hunk 1]
```diff
@@ -261,47 +261,43 @@ class MetadataParser {
...
+    return ["spatialBounding": spatialBounding, "isGlobal": isGlobal]
   }
 
-  static def parseCoords(def bbox){
-    def westBound = (bbox.westBoundLongitude == "null" ||  bbox.westBoundLongitude == "") ? null : bbox.westBoundLongitude.Decimal.toFloat()
-    def eastBound = (bbox.eastBoundLongitude == "null" ||  bbox.eastBoundLongitude == "") ? null : bbox.eastBoundLongitude.Decimal.toFloat()
-    def northBound = (bbox.northBoundLatitude == "null" || bbox.northBoundLatitude == "")  ? null : bbox.northBoundLatitude.Decimal.toFloat()
-    def southBound = (bbox.southBoundLatitude == "null" || bbox.southBoundLatitude == "") ? null : bbox.southBoundLatitude.Decimal.toFloat()
+  static def parseBounding(def bbox) {
+    if (!bbox) { return null }
```
Comment (zebdelk) [inline api/src/main/groovy/ncei/onestop/api/service/MetadataParser.groovy]: Before, no bbox meant spacialBounding defaulted to [:], not null. Is that going to be an issue?

File: api/src/main/groovy/ncei/onestop/api/service/MetadataParser.groovy [hunk 2]
```diff
@@ -261,47 +261,43 @@ class MetadataParser {
...
-    return [
-          [westBound, northBound],
-          [eastBound, southBound]
-    ]
+    def west = (bbox.westBoundLongitude == "null" ||  bbox.westBoundLongitude == "") ? null : bbox.westBoundLongitude.Decimal.toFloat()
+    def east = (bbox.eastBoundLongitude == "null" ||  bbox.eastBoundLongitude == "") ? null : bbox.eastBoundLongitude.Decimal.toFloat()
+    def north = (bbox.northBoundLatitude == "null" || bbox.northBoundLatitude == "")  ? null : bbox.northBoundLatitude.Decimal.toFloat()
+    def south = (bbox.southBoundLatitude == "null" || bbox.southBoundLatitude == "") ? null : bbox.southBoundLatitude.Decimal.toFloat()
+
+    if (!west || !east || !north || !south) { return null }
```
Comment (zebdelk) [inline api/src/main/groovy/ncei/onestop/api/service/MetadataParser.groovy]: Ditto above comment with this return null

File: api/src/test/groovy/ncei/onestop/api/service/MetadataParserTest.groovy [hunk 3]
```diff
@@ -214,18 +213,18 @@ class MetadataParserTest extends Specification {
...
-                    type       : 'envelope',
-                    coordinates: [
-                            [-180, 90],
-                            [180, -90]
-                    ]
-            ],
-            isGlobal: true]
+    result == [
+        spatialBounding: [
+            type: 'polygon',
```
Comment (zebdelk) [inline api/src/test/groovy/ncei/onestop/api/service/MetadataParserTest.groovy]: Since we added support for points as well as polygons, should we add a test for that? Also, is there a reason we don't also have a test in here for a non-global example?

Comment (mcquinne) [reply api/src/test/groovy/ncei/onestop/api/service/MetadataParserTest.groovy]: Good idea. Added a test with a point geometry (which is also non-global).

File: api/src/main/groovy/ncei/onestop/api/service/MetadataParser.groovy (hunk 1 above)
Comment (mcquinne) [reply api/src/main/groovy/ncei/onestop/api/service/MetadataParser.groovy]: Tested against the ES API directly and sending null for the spatialBounding field works just fine, and actually sending an empty object doesn't work. I think the Java Client is making it work for us either way, though this way will port more easily to the ES 5.x branch.

File: api/src/main/groovy/ncei/onestop/api/service/MetadataParser.groovy (hunk 2 above)
Comment (mcquinne) [reply api/src/main/groovy/ncei/onestop/api/service/MetadataParser.groovy]: See above
